#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

mainlib = helper.make_mainlib ( [
    'art_Utilities',
    'canvas',
    'cetlib',
    'cetlib_except',
    'mu2e_RecoDataProducts',
] )

helper.make_plugins( [
    mainlib,
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Persistency_Provenance',
    'art_Utilities',
    'canvas',
    'cetlib',
    'cetlib_except',
    'fhiclcpp',
    'fhiclcpp_types',
    'mu2e_DataProducts',
    'mu2e_RecoDataProducts',
] )

helper.make_dict_and_map( [
    mainlib,
    'Core',
    'art_Utilities',
    'canvas',
    'cetlib',
    'cetlib_except',
    'canvas'
] )
